services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    NewsBundle\EventListener\NewsSeoListener:
        tags:
            - { name: kernel.event_subscriber }

    NewsBundle\EventListener\EntryTypeListener:
        tags:
            - { name: kernel.event_subscriber }

    NewsBundle\EventListener\MetaDataListener:
        tags:
            - { name: kernel.event_subscriber }
