services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    NewsBundle\Generator\LinkGeneratorInterface: '@NewsBundle\Generator\LinkGenerator'
    NewsBundle\Generator\LinkGenerator: ~

    NewsBundle\Generator\RelatedEntriesGeneratorInterface: '@NewsBundle\Generator\RelatedEntriesGenerator'
    NewsBundle\Generator\RelatedEntriesGenerator: ~

    NewsBundle\Generator\HeadMetaGeneratorInterface: '@NewsBundle\Generator\HeadMetaGenerator'
    NewsBundle\Generator\HeadMetaGenerator: ~
