services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    NewsBundle\Tool\Install:
        arguments:
            $bundle: "@=service('kernel').getBundle('NewsBundle')"
        calls:
            - [setTokenStorageUserResolver, ['@Pimcore\Security\User\TokenStorageUserResolver']]
            - [setSerializer, ['@serializer']]

    NewsBundle\Configuration\Configuration: ~

    NewsBundle\Controller\Admin\SettingsController:
        public: true
        autowire: true
        arguments:
            $adminTranslator: '@Pimcore\Bundle\AdminBundle\Translation\AdminUserTranslator'
        tags: ['controller.service_arguments']